# importing labels

In [4]:
import numpy as np_1961
from pandas import DataFrame

 # random numbers generate in DataFrame

In [6]:
np.random.randint(19,61,[8,8])

NameError: name 'np' is not defined

In [16]:
df

0   1   2   3   4   5   6   7
0  31  38  25  60  44  49  32  57
1  25  44  21  39  31  47  37  20
2  57  57  31  57  56  25  54  51
3  32  34  39  54  19  32  26  22
4  25  35  37  50  58  51  44  51
5  32  52  47  19  35  37  33  53
6  28  40  44  40  27  30  55  46
7  50  41  59  45  38  35  48  47

# Slider in diapazone

In [19]:
def trig_OG_slider(diagonal_rectangle='true diagonal ?' , up_to_vector='Up values?', normal_vector='append diagonal vector?', _df_=df):
    
    
    data=[]
    if diagonal_rectangle:
        if up_to_vector==True:
            if normal_vector:
                [[data.append(_df_[column][index]) if column>index or column==index else data.append(None) for index in _df_.index] for column in _df_.columns]   
            else:
                [[data.append(_df_[column][index]) if column>index and column!=index else data.append(None) for index in _df_.index] for column in _df_.columns]
        elif up_to_vector==False:
            if normal_vector:
                [[data.append(_df_[column][index]) if column<index or column==index else data.append(None) for index in _df_.index] for column in _df_.columns]
            else:
                [[data.append(_df_[column][index]) if column<index and column!=index else data.append(None) for index in _df_.index] for column in _df_.columns]
        else:
            print('Errors in up_asker ')
    
    elif diagonal_rectangle==False:
        if type(up_to_vector)==str:
                                
                                
                                
        if up_to_vector==True:
            if normal_vector:
                [[data.append(_df_[column][index]) if index+column<len(df) else data.append(None) for index in _df_.index] for column in _df_.columns]   
            else:
                [[data.append(_df_[column][index]) if (index+column<len(df)-1 and column<=index) or index+column<len(df)-1 else data.append(None) for index in _df_.index] for column in _df_.columns]
        
        elif up_to_vector==False:
            if normal_vector:
                [[data.append(_df_[column][index]) if index+column>len(df)-2 else data.append(None) for index in _df_.index] for column in _df_.columns]   
            else:
                [[data.append(_df_[column][index]) if index+column>len(df)-1 else data.append(None) for index in _df_.index] for column in _df_.columns]
        else:
            print('Errors in up_asker ')
    
    else:
        print('Errors in diagonal_select ')
    
    data=np_1961.array(data)
    data.shape=_df_.shape
    data=DataFrame(data)
    return data

IndentationError: expected an indented block (<ipython-input-19-aa77e52780fb>, line 23)

In [423]:
trig_OG_slider(diagonal_rectangle=False, up_to_vector=True, normal_vector=False, _df_=df)

0     1     2     3     4     5     6     7     8     9
0    36    24    55    40    23    38    49    22    53  None
1    32    38    36    36    43    46    49    52  None  None
2    20    30    27    55    20    29    24  None  None  None
3    42    30    50    53    39    23  None  None  None  None
4    33    30    52    52    51  None  None  None  None  None
5    48    26    48    60  None  None  None  None  None  None
6    35    28    52  None  None  None  None  None  None  None
7    38    26  None  None  None  None  None  None  None  None
8    38  None  None  None  None  None  None  None  None  None
9  None  None  None  None  None  None  None  None  None  None

# DataFrame numbers to numpy array 

In [418]:
none_numbers=[]
numbers=[]
values=np_1961.array(trig_OG_slider(diagonal_rectangle=False, up_to_vector=True, normal_vector=False, _df_=df).values)
values

array([[36, 24, 55, 40, 23, 38, 49, 22, 53, None],
       [32, 38, 36, 36, 43, 46, 49, 52, None, None],
       [20, 30, 27, 55, 20, 29, 24, None, None, None],
       [42, 30, 50, 53, 39, 23, None, None, None, None],
       [33, 30, 52, 52, 51, None, None, None, None, None],
       [48, 26, 48, 60, None, None, None, None, None, None],
       [35, 28, 52, None, None, None, None, None, None, None],
       [38, 26, None, None, None, None, None, None, None, None],
       [38, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None]],
      dtype=object)

In [419]:
[[numbers.append(element) if element!=None else none_numbers.append(0) for element in elements] for elements in values]

[[None, None, None, None, None, None, None, None, None, None],
 [None, None, None, None, None, None, None, None, None, None],
 [None, None, None, None, None, None, None, None, None, None],
 [None, None, None, None, None, None, None, None, None, None],
 [None, None, None, None, None, None, None, None, None, None],
 [None, None, None, None, None, None, None, None, None, None],
 [None, None, None, None, None, None, None, None, None, None],
 [None, None, None, None, None, None, None, None, None, None],
 [None, None, None, None, None, None, None, None, None, None],
 [None, None, None, None, None, None, None, None, None, None]]

In [420]:
np_1961.array(numbers)/90

array([36, 24, 55, 40, 23, 38, 49, 22, 53, 32, 38, 36, 36, 43, 46, 49, 52,
       20, 30, 27, 55, 20, 29, 24, 42, 30, 50, 53, 39, 23, 33, 30, 52, 52,
       51, 48, 26, 48, 60, 35, 28, 52, 38, 26, 38])

In [421]:
np_1961.array(none_numbers)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])